name: CI

on:
  - push
  - pull_request

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bardinpetr/ocaml-llvm:latest
      options: --user root --cpus 1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_GITHUB_TOKEN }}
    steps:
      - name: checkout
        run: git clone https://github.com/BardinPetr/ocaml-llvm-c-frontend /root/app
        working-directory: /root
      - name: prepare
        working-directory: /root/app
        run: chmod +x ci.sh
      - name: run
        working-directory: /root/app
        run: ./ci.sh
