name: CI

on:
  - push
  - pull_request

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bardinpetr/ocaml-llvm:latest
      options: --user root --cpus 1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_GITHUB_TOKEN }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
